### ISSUE TITLE
Prepare project plan

### ISSUE THREAD

**Issue by ilammy** [apriorit/linux-vpn-2017-autumn#2]
Нужно спланировать работу по проекту.

- [x] **Примерный план**

Здесь следует пересчислить примерное разбиение времени по крупным задачам (с точностью около недели). Дата сдачи проекта фиксирована, это следует учитывать в планах. Так что напишите её здесь, пожалуйста, чтобы не потерялась.

Не забудьте включить в план следующие пункты:

  * исследование реализуемости, написание прототипов
  * составление уточнённого плана
  * задачи по разработке проекта
  * тестирование, исправление обнаруженных недостатков
  * написание документации
  * подготовка к защите проекта

План следует приложить к этой задаче в любой удобной форме. Лучше просто текстом прямо сюда в комментарии (так читать проще), но можно прикрепить файл.

**Срок:** 2017-10-11 (среда)

- [x] **Уточнённый план**

Далее потребуется уточнить задачи, сформулированные в примерном плане, распределить задачи между собой, оценить время их выполнения, и выдать вердикт: успеваем ли мы к поставленному сроку.

Обратите внимание: время надо _оценивать, а не разделять_. То есть разбиение на подзадачи производится сверху вниз (от крупных задач к маленьким подзадачам), но оценка времени — снизу вверх. Время на задачи должно складываться из времени на подзадачи, а не наоборот. Не следует выделять время на подзадачи исходя из того, сколько времени ещё остаётся на главную задачу. Если вам не ясно, сколько времени потребуется на подзадачу, то её следует разбивать на более мелкие подзадачи.

Желаемое разрешение этого плана (типичный размер подзадачи): около двух-трёх дней.

**Срок:** 2017-10-20 (пятница) ❓

**Comment by Ranege** [comment]
[vpn_project_plan.zip](https://github.com/apriorit/linux-vpn-2017-autumn/files/1403280/vpn_project_plan.zip)

**Comment by ilammy** [comment]
@Ranege, @rzr707, 👍 хороший план, достаточно детализированный.
